typecast of gl_FrontFacing should match with type of destination Input
code:
  uvec4 Input7
  Input7.x = uint(gl_FrontFacing);

cause: error C7011: implicit cast from "int" to "uint"
at least at NVidia GF960